config/routes.rb
Rails.application.routes.draw do
  resources :reports do
   resources :newcomments, only: [:new, :create]
  end
  devise_for :pc_users, controllers: {
    sessions: 'pc_users/sessions',
    registrations: 'pc_users/registrations'
  }
  get 'home/index'

  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
 
  # Defines the root path route ("/")
   root "reports#index"
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
  <div class="container">
  <%= link_to "TheRialNews", root_path, class: "navbar-brand"%>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse " id="navbarNavDropdown">
      <ul class="navbar-nav me-auto">
      <li>
      <%= link_to "Report", reports_path, class: "nav-link"%>
      </li>
      </ul>
      <ul class="navbar-nav ms-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <% if pc_user_signed_in? %>
            <% if current_pc_user.name %>
              Hola <%= current_pc_user.name %>!
            <% else %>
            Hola <%= current_pc_user.email %>
            <%end%>
            <%else%>
              Debes Registrarte
            <% end %>
          </a>
          <ul class="dropdown-menu">
            <% if pc_user_signed_in? %>
              <li><%= button_to "Cerrar sesión", destroy_pc_user_session_path, class:"dropdown-item", method: :delete %></li>
            <% end %>
            <li><%= link_to "Iniciar sesión", new_pc_user_session_path, class:"dropdown-item" %></li>
            <li><%= link_to "Registro", new_pc_user_registration_path, class:"dropdown-item" %></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>