config/routes.rb
Rails.application.routes.draw do
  resources :reports do
   resources :newcomments, only: [:new, :create]
  end
  devise_for :pc_users, controllers: {
    sessions: 'pc_users/sessions',
    registrations: 'pc_users/registrations'
  }
  get 'home/index'

  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
 
  # Defines the root path route ("/")
   root "reports#index"
end

app/models/newcomment.rb
class Newcomment < ApplicationRecord
  belongs_to :pc_user
  belongs_to :report
end

app/controllers/newcomments_controller.rb
class NewcommentsController < ApplicationController
  before_action :set_newcomment, only: %i[ show edit update destroy ]
  before_action :set_report
  before_action :authenticate_pc_user!, except: %i[index show]
  before_action :newcomment_permission, only: %i[ edit destroy]
  before_action only: [:create, :new ] do
    authorize_request(["normal_pc_user"])
  end

  before_action only: [:edit, :update, :destroy] do
    authorize_request(["admin"])
  end

  # GET /newcomments or /newcomments.json
  def index
    @newcomments = @report.newcomments
    end

  # GET /newcomments/1 or /newcomments/1.json
  def show
  end

  # GET /newcomments/new
  def new
    @newcomment = @report.newcomments.new
  end

  # GET /newcomments/1/edit
  def edit
  end

  # POST /newcomments or /newcomments.json
  def create
    @newcomment = @report.newcomments.new(newcomment_params)
    @newcomment.user = current_pc_user

    respond_to do |format|
      if @newcomment.save
        format.html { redirect_to report_newcomment_path(@report.id,@newcomment.id), notice: "Newcomment was successfully created." }
        format.json { render :show, status: :created, location: @newcomment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @newcomment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /newcomments/1 or /newcomments/1.json
  def update
    respond_to do |format|
      if @newcomment.update(newcomment_params)
        format.html { redirect_to newcomment_url(@newcomment), notice: "Newcomment was successfully updated." }
        format.json { render :show, status: :ok, location: @newcomment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @newcomment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /newcomments/1 or /newcomments/1.json
  def destroy
    @newcomment.destroy

    respond_to do |format|
      format.html { redirect_to newcomments_url, notice: "Newcomment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_newcomment
      @newcomment = Newcomment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def newcomment_params
      params.require(:newcomment).permit(:body, :pc_user_id, :report_id)
    end
    def set_report
      @report =Report.find(params[:report_id])
  end
  def newcomment_permission
    unless @newcomment.pc_user_id == current_pc_user.id || current_pc_user.role !=2
      redirect_to report_newcomment_path(@report.id), notice: 'You are not allowed to perform this action'
    end    
  end
end

app/helpers/newcomments_helper.rb
module NewcommentsHelper
end

app/views/newcomments/_form.html.erb
<%= form_with(model: [@report, newcomment]) do |form| %>
  <% if newcomment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(newcomment.errors.count, "error") %> prohibited this newcomment from being saved:</h2>

      <ul>
        <% newcomment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.label :pc_user_id, style: "display: block" %>
    <strong><%= current_pc_user.email %></strong>
  </div>

  <div>
    <%= form.label :report_id, style: "display: block" %>
    <strong><%= @report.id %></strong>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/newcomments/_newcomment.html.erb
<div id="<%= dom_id newcomment %>">
  <p>
    <strong>Body:</strong>
    <%= newcomment.body %>
  </p>

  <p>
    <strong>Pcuser:</strong>
    <%= newcomment.pc_user_id %>
  </p>

  <p>
    <strong>Report:</strong>
    <%= newcomment.report_id %>
  </p>

</div>

app/views/newcomments/edit.html.erb
<h1>Editing newcomment</h1>

<%= render "form", newcomment: @newcomment %>

<br>

<div>
  <%= link_to "Show this newcomment", report_newcomment_path(resport.id,@newcomment.id) %> |
  <%= link_to "Back to newcomments", report_newcomment_path(@report.id) %>
</div>

app/views/newcomments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Newcomments</h1>

<div id="newcomments">
  <% @newcomments.each do |newcomment| %>
    <%= render newcomment %>
    <p>
      <%= link_to "Show this newcomment", report_comment_path(@report.id, @newcomment.id)  %>
    </p>
  <% end %>
</div>

<%= link_to "New newcomment", new_report_newcomment_path(@report.id) %>

app/views/newcomments/new.html.erb
<h1>New newcomment</h1>

<%= render "form", newcomment: @newcomment %>

<br>

<div>
  <%= link_to "Back to newcomments", report_newcomments_path(@report.id) %>
</div>

app/views/newcomments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @newcomment %>

<div>
<%= link_to "Back to newcomments", report_newcomments_path(@report.id) %>
<% if @newcomment.user_id == current_user.id || current_pc_user.role == "admin"%>
<%= link_to "Edit this newcomment", edit_report_newcomment_path(@report.id, @newcomment.id) %> |
  
  <%= button_to "Destroy this newcomment", report_newcomment_path(@report.id, @newcomment.id), method: :delete %>
<%end %>
</div>