config/routes.rb
Rails.application.routes.draw do
  resources :reports do
   resources :newcomments, only: [:new, :create]
  end
  devise_for :pc_users, controllers: {
    sessions: 'pc_users/sessions',
    registrations: 'pc_users/registrations'
  }
  get 'home/index'

  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
 
  # Defines the root path route ("/")
   root "reports#index"
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :pc_user
  has_many :reports
  has_many :newsComments

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: %i[ show edit update destroy ]
  before_action :authenticate_pc_user!, except: %i[ index show]
  before_action only: [:new, :create] do
    authorize_request(["author","admin"])
  end 
  before_action only:[ :edit, :update, :destroy] do
    authorize_request(["admin"])
  end
  # GET /reports or /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1 or /reports/1.json
  def show
    
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports or /reports.json
  def create
    @report = Report.new(report_params)
    @report.pc_user = current_pc_user

    respond_to do |format|
      if @report.save
        format.html { redirect_to report_url(@report), notice: "Report was successfully created." }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1 or /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to report_url(@report), notice: "Report was successfully updated." }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1 or /reports/1.json
  def destroy
    @report.destroy

    respond_to do |format|
      format.html { redirect_to reports_url, notice: "Report was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def report_params
      params.require(:report).permit(:title, :description, :pc_user_id)
    end
  end  

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<%= form_with(model: report) do |form| %>
  <% if report.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
        <% report.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :pc_user_id, style: "display: block" %>
    <%= form.text_field :pc_user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/reports/_report.html.erb
<div id="<%= dom_id report %>">
  <p>
    <strong>Title:</strong>
    <%= report.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= report.description %>
  </p>

  <p>
    <strong>Pcuser:</strong>
    <%= report.pc_user_id %>
  </p>

</div>

app/views/reports/edit.html.erb
<h1>Editing report</h1>

<%= render "form", report: @report %>

<br>

<div>
  <%= link_to "Show this report", @report %> |
  <%= link_to "Back to reports", reports_path %>
</div>

app/views/reports/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Reports</h1>

<div id="reports">
  <% @reports.each do |report| %>
    <%= render report %>
    <p>
      <%= link_to "Show this report", report %>
    </p>
  <% end %>
</div>
<% if pc_user_signed_in? %>
    <% if current_pc_user.role == "admin" %>
      <%= link_to "New report", new_report_path %>
  <% end %>
<% end%>

app/views/reports/new.html.erb
<h1>New report</h1>

<%= render "form", report: @report %>

<br>

<div>
  <%= link_to "Back to reports", reports_path %>
</div>

app/views/reports/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @report %>

<div>
  <% if pc_user_signed_in? %>
    <% if current_pc_user.role == "admin" %>
  <%= link_to "Edit this report", edit_report_path(@report) %> |
  <%= button_to "Destroy this report", @report, method: :delete %>
  <% end %>
<% end %>
<%= link_to "Back to reports", reports_path %> | 
<%= link_to "New Comment", new_report_newcomment_path(@report)%>
  
</div>